services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: investment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: ankatech
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: mysql://user:password@db:3307/investment_db
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && node dist/index.js"

volumes:
  mysql_data:
